# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
- repo: self

trigger:
  none

variables:
  system.debug: true
  
stages:
- stage: Deploy
  displayName: Deploy db and run migrator
  jobs:
  - job: 
    displayName: Deploy db and run migrator
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          telnet 20.39.210.5 22