trigger:
  none

pool:
  name: internal-agent

resources:
- repo: self

jobs:
- job: ApplyKubernetesJob
  displayName: 'Apply Kubernetes Job'
  pool:
    name: internal-agent
  variables:
  - name: imageVersion
    value: v1
  - name: jobName
    value: migration-service
    
  steps:
  - task: KubeloginInstaller@0
    inputs:
      kubeloginVersion: 'latest'
  - task: Kubernetes@1
    displayName: Delete Job $(jobName)
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: 'internal-adm-sp'
      azureResourceGroup: 'internal-ptae-rg-01'
      kubernetesCluster: 'internal-ptae-aks-01'
      namespace: 'dev'
      command: 'delete'
      arguments: 'job $(jobName)'

  - task: replacetokens@5
    inputs:
      rootDirectory: '$(Build.SourcesDirectory)'
      targetFiles: '**/migration-service.yaml'
      encoding: 'auto'
      tokenPattern: 'azpipelines'
      writeBOM: true
      actionOnMissing: 'warn'
      keepToken: false
      actionOnNoFiles: 'warn'
      enableTransforms: false
      enableRecursion: false
      useLegacyPattern: false
      enableTelemetry: true

  - task: Kubernetes@1
    displayName: Create Job $(jobName)
    env:
      imageVersion: "latest"
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: 'internal-adm-sp'
      azureResourceGroup: 'internal-ptae-rg-01'
      kubernetesCluster: 'internal-ptae-aks-01'
      namespace: 'dev'
      command: 'apply'
      arguments: '-f $(Build.SourcesDirectory)/migration-service.yaml'
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'

