# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  docker.username : 'ptaeventscontainerregistry'
  docker.password : 'H+hguwyvOT9c9cREt5UAmKWt7I+fCUXpi9cMkjUTMp+ACRDz8txv'
  docker.registry: 'ptaeventscontainerregistry.azurecr.io'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'ssh_to_hyve_dev_vps'
        targetFolder: 'deploy'
        contents: docker-compose.yml
        readyTimeout: '20000'
    - task: SSH@0
      inputs:
        sshEndpoint: 'ssh_to_hyve_dev_vps'
        runOptions: 'commands'
        commands: |
          sudo docker login -u $(docker.username) -p $(docker.password) $(docker.registry) 
          cd deploy 
          docker-compose pull 
          docker-compose stop
          docker-compose rm -f
          docker-compose up -d
        readyTimeout: '20000'
    
