trigger:
  none

pool:
  name: internal-agent

resources:
- repo: self

jobs:
- job: ApplyKubernetesJob
  displayName: 'Apply Kubernetes Job'
  pool:
    name: internal-agent
  variables:
  - name: imageVersion
    value: latest
    
  steps:
  - task: KubeloginInstaller@0
    inputs:
      kubeloginVersion: 'latest'
  - task: Kubernetes@1
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: 'internal-adm-sp'
      azureResourceGroup: 'internal-ptae-rg-01'
      kubernetesCluster: 'internal-ptae-aks-01'
      namespace: 'dev'
      command: 'apply'
      arguments: '-f $(Build.SourcesDirectory)/migration-service.yaml'
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'
