trigger:
  none

pool:
  name: internal-agent

resources:
- repo: self

jobs:
- job: ApplyKubernetesJob
  displayName: 'Apply Kubernetes Job'
  pool:
    name: internal-agent
  steps:
  - task: KubectlInstaller@0
    inputs:
      kubectlVersion: 'latest'
  - task: UseKubectl@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: '<YOUR_K8S_SERVICE_CONNECTION>'
      command: 'apply'
      arguments: '-f $(Build.SourcesDirectory)/migration-service.yaml'

  - task: KubeloginInstaller@0
    inputs:
      kubeloginVersion: 'latest'
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'internal(31ee4a72-709d-4b02-bd0e-30b59dee8a4c)'
    azureResourceGroup: 'internal-ptae-rg-01'
    kubernetesCluster: 'internal-ptae-aks-01'
    namespace: 'dev'
    manifests: '$(Build.SourcesDirectory)/migration-service.yaml'

    