# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'ssh_to_hyve_dev_vps'
        targetFolder: 'deploy'
        contents: |
                  docker-compose.yaml
                  Docker
        readyTimeout: '20000'
    - task: SSH@0
      inputs:
        sshEndpoint: 'ssh_to_hyve_dev_vps'
        runOptions: 'commands'
        commands: |
          cd deploy
          sudo docker container stop $(sudo docker container ls -aq)
          sudo docker container prune -f
          sudo docker compose up -d
        readyTimeout: '20000'
    
