# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
- repo: self

trigger:
  none

variables:
  system.debug: true
  
stages:
- stage: Deploy
  displayName: Deploy db and run migrator
  jobs:
  - job: 
    displayName: Deploy db and run migrator
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'ssh_to_hyve_dev_vps'
        targetFolder: 'dbandmigrator'
        contents: |
                  **
        readyTimeout: '20000'
    - task: SSH@0
      inputs:
        sshEndpoint: 'ssh_to_hyve_dev_vps'
        failOnStdErr: false
        runOptions: 'commands'
        commands: |
           cd dbandmigrator && sudo docker compose down && sudo docker compose up -d --build
        readyTimeout: '20000'
    
