# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure subscription 1(31ee4a72-709d-4b02-bd0e-30b59dee8a4c)'
        azureContainerRegistry: '{"loginServer":"ptaeventscontainerregistry.azurecr.io", "id" : "/subscriptions/31ee4a72-709d-4b02-bd0e-30b59dee8a4c/resourceGroups/ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/ptaeventscontainerregistry"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'docker compose up'
    
