version: '3.4'

services:
  mariadbfluentmigrationservice:
    image: mariadbfluentmigrationservice
    networks:
      - db_network
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
        mariadb:
            condition: service_healthy
    restart: on-failure

  mariadb:
    image: mariadb:10.5
    networks:
      - db_network
    volumes:
    - type: volume
      source: mariadb-data
      target: /var/lib/mysql
    environment:
        MARIADB_ROOT_PASSWORD : j@w@3cr1pt
        MARIADB_DATABASE : ptaevent
    ports: 
         - 3307:3306
    command: ['mysqld', '--character-set-server=latin1', '--collation-server=latin1_swedish_ci']
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
volumes:
    mariadb-data:

networks:
  db_network:
    name: db_network
    external: true