apiVersion: batch/v1
kind: Job
metadata:
  name: migration-service
spec:
  template:
    spec:
      containers:
        - name: migration-service
          image: azcentralcr.azurecr.io/fluent-migration-service:$(tag)
      restartPolicy: Never
  backoffLimit: 4
